#pragma once

// Number of individual voices
// Now works only with <= 4
#define SYNTH_NUM_VOICES 4

// Definitions for 12TET conversions
#define SYNTH_BASE_NOTE A4
#define SYNTH_BASE_FREQ 440.0f

#define SYNTH_IDLE_TIME_S 5
#define SYNTH_DISPLAY_UPDATE_PERIOD_MS 100

// Clock configuration
#define SYNTH_HSE_FREQUENCY_MHZ 8
#define SYNTH_SYSCLK_FREQUENCY_MHZ 168

// Interrupt priorities relative to
// configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY
#define SYNTH_PWM_TIM_IRQ_PRIORITY_REL -1
#define SYNTH_USB_OTG_IRQ_PRIORITY_REL 0

// FreeRTOS application options
#define SYNTH_NOTE_EVENT_QUEUE_SIZE 32

#define SYNTH_NOTE_HANDLER_TASK_STACK_SIZE 512
#define SYNTH_NOTE_HANDLER_TASK_PRIORITY 2

#define SYNTH_USB_MIDI_TASK_STACK_SIZE 512
#define SYNTH_USB_MIDI_TASK_PRIORITY 2

#define SYNTH_DISPLAY_TASK_STACK_SIZE 512
#define SYNTH_DISPLAY_TASK_PRIORITY 1